apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustdb-data-pvc
  namespace: rustdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustdb-logs-pvc
  namespace: rustdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

